const Words: string[] = [
    'Rain_',
    'blank_',
    'Air_',
    'Fire_',
    'Banana_',
    'Dog_',
    'Fish_',
    'Plane_',
    'Car_',
    'Ice_',
    'Snow_',
    'Nose_',
    'I\'m_',
    'Trust_',
    'Believe_',
    'It\'s_',
    'Night_',
    'Breaking_',
    'Risk_',
    'House_',
    'Party_',
    'Music_',
    'Space_',
    'Test_',
    'Game_',
    'Funny_',
    'Bad_',
    'Silver_',
    '_Crane',
    '_Jam',
    '_Cheese',
    '_Bean',
    '_League',
    '_Pad',
    '_Day',
    'Day_',
    'Great_',
    '_Button',
    '_Jacket',
    '_Moon',
    '_Syrup',
    'Hard_',
    '_Burger',
    'Fast_',
    'Rock_',
    'Fat_',
    '_Paper',
    'Light_',
    'Full_',
    '_Board',
    'Hand_',
    '_Jack',
    '_List',
    '_Party',
    'Bad_',
    'Happy_',
    'Square_',
    '_Point',
    'Naked_',
    '_Cat',
    'Movie_',
    'Eye_',
    'Banana_',
    'Dinner_',
    'Head_',
    'Easter_',
    'Carrot_',
    'Upper_',    
];

const getRandomWord = (previousWords: string[]): string => {
    const words = Words.filter((word) => !previousWords.includes(word));
    const randomIndex = Math.floor(Math.random() * words.length);
    return words[randomIndex] ?? "out of words";
}

export default getRandomWord;